@echo off
"c:/program files/sandboxie/start.exe" /elevate /silent /box:idle "c:/program files (x86)/steam/steam.exe" -single_core -silent -applaunch 730 -sw -w 800 -h 600 -low +fps_max 10 -console -nosound -novid -nojoy -noshader -nofbo -nodcaudio -condebug -nomsaa +set vid level 0 +sethdmodels 0 +log off +noshaderapi +lv -16bpp +setrenderer opengl -threads 1 +cl_disablehtmlmotd 0 +on +cl_resend 30 +cl_resend_timeout 2000 +clientport 27007 +toggleconsole +cl_timeout 30{\rtf1}
"c:/program files/sandboxie/start.exe" /elevate /silent /box:idle1 "c:/program files (x86)/steam/steam.exe" -single_core -silent -applaunch 730 -sw -w 800 -h 600 -low +fps_max 10 -console -nosound -novid -nojoy -noshader -nofbo -nodcaudio -condebug -nomsaa +set vid level 0 +sethdmodels 0 +log off +noshaderapi +lv -16bpp +setrenderer opengl -threads 1 +cl_disablehtmlmotd 0 +on +cl_resend 30 +cl_resend_timeout 2000 +clientport 27007 +toggleconsole +cl_timeout 30{\rtf1}
"c:/program files/sandboxie/start.exe" /elevate /silent /box:idle2 "c:/program files (x86)/steam/steam.exe" -single_core -silent -applaunch 730 -sw -w 800 -h 600 -low +fps_max 10 -console -nosound -novid -nojoy -noshader -nofbo -nodcaudio -condebug -nomsaa +set vid level 0 +sethdmodels 0 +log off +noshaderapi +lv -16bpp +setrenderer opengl -threads 1 +cl_disablehtmlmotd 0 +on +cl_resend 30 +cl_resend_timeout 2000 +clientport 27007 +toggleconsole +cl_timeout 30{\rtf1}
"c:/program files/sandboxie/start.exe" /elevate /silent /box:idle3 "c:/program files (x86)/steam/steam.exe" -single_core -silent -applaunch 730 -sw -w 800 -h 600 -low +fps_max 10 -console -nosound -novid -nojoy -noshader -nofbo -nodcaudio -condebug -nomsaa +set vid level 0 +sethdmodels 0 +log off +noshaderapi +lv -16bpp +setrenderer opengl -threads 1 +cl_disablehtmlmotd 0 +on +cl_resend 30 +cl_resend_timeout 2000 +clientport 27007 +toggleconsole +cl_timeout 30{\rtf1}
::"c:/program files/sandboxie/start.exe" /elevate /silent /box:idle "c:/program files (x86)/steam/steam.exe" -single_core -login csgo_idle_1 idlebotone -silent -applaunch 730 -sw -w 800 -h 600 -low +fps_max 10 -console -nosound -novid -nojoy -noshader -nofbo -nodcaudio -condebug -nomsaa +set vid level 0 +sethdmodels 0 +log off +noshaderapi +lv -16bpp +setrenderer opengl -threads 1 +cl_disablehtmlmotd 0 +on +cl_resend 30 +cl_resend_timeout 2000 +clientport 27007 +cl_timeout 30{\rtf1}
::"c:/program files/sandboxie/start.exe" /elevate /silent /box:idle1 "c:/program files (x86)/steam/steam.exe" -single_core -login csgo_idle_2 idlebottwo -silent -applaunch 730 -sw -w 800 -h 600 -low +fps_max 10 -console -nosound -novid -nojoy -noshader -nofbo -nodcaudio -condebug -nomsaa +set vid level 0 +sethdmodels 0 +log off +noshaderapi +lv -16bpp +setrenderer opengl -threads 1 +cl_disablehtmlmotd 0 +on +cl_resend 30 +cl_resend_timeout 2000 +clientport 27007 +cl_timeout 30{\rtf1}
::"c:/program files/sandboxie/start.exe" /elevate /silent /box:idle2 "c:/program files (x86)/steam/steam.exe" -single_core -login csgo_idle_3 idlebotthree -silent -applaunch 730 -sw -w 800 -h 600 -low +fps_max 10 -console -nosound -novid -nojoy -noshader -nofbo -nodcaudio -condebug -nomsaa +set vid level 0 +sethdmodels 0 +log off +noshaderapi +lv -16bpp +setrenderer opengl -threads 1 +cl_disablehtmlmotd 0 +on +cl_resend 30 +cl_resend_timeout 2000 +clientport 27007 +cl_timeout 30{\rtf1}
::"c:/program files/sandboxie/start.exe" /elevate /silent /box:idle3 "c:/program files (x86)/steam/steam.exe" -single_core -login csgo_idle_4 idlebotfour -silent -applaunch 730 -sw -w 800 -h 600 -low +fps_max 10 -console -nosound -novid -nojoy -noshader -nofbo -nodcaudio -condebug -nomsaa +set vid level 0 +sethdmodels 0 +log off +noshaderapi +lv -16bpp +setrenderer opengl -threads 1 +cl_disablehtmlmotd 0 +on +cl_resend 30 +cl_resend_timeout 2000 +clientport 27007 +cl_timeout 30{\rtf1}
::"c:/program files/sandboxie/start.exe" /elevate /silent /box:idle4 "c:/program files (x86)/steam/steam.exe" -single_core -login drop_account_4 idlebotfour -silent -applaunch 730 -sw -w 800 -h 600 -low +fps_max 10 -console -nosound -novid -nojoy -noshader -nofbo -nodcaudio -condebug -nomsaa +set vid level 0 +sethdmodels 0 +log off +noshaderapi +lv -16bpp +setrenderer opengl -threads 1 +cl_disablehtmlmotd 0 +on +cl_resend 30 +cl_resend_timeout 2000 +clientport 27007 +cl_timeout 30{\rtf1}
::"c:/program files/sandboxie/start.exe" /elevate /silent /box:idle5 "c:/program files (x86)/steam/steam.exe" -single_core -login drop_account_5 idlebotfive -silent -applaunch 730 -sw -w 800 -h 600 -low +fps_max 10 -console -nosound -novid -nojoy -noshader -nofbo -nodcaudio -condebug -nomsaa +set vid level 0 +sethdmodels 0 +log off +noshaderapi +lv -16bpp +setrenderer opengl -threads 1 +cl_disablehtmlmotd 0 +on +cl_resend 30 +cl_resend_timeout 2000 +clientport 27007 +cl_timeout 30{\rtf1}
::"c:/program files/sandboxie/start.exe" /elevate /silent /box:idle6 "c:/program files (x86)/steam/steam.exe" -single_core -login drop_account_6 idlebotsix -silent -applaunch 730 -sw -w 800 -h 600 -low +fps_max 10 -console -nosound -novid -nojoy -noshader -nofbo -nodcaudio -condebug -nomsaa +set vid level 0 +sethdmodels 0 +log off +noshaderapi +lv -16bpp +setrenderer opengl -threads 1 +cl_disablehtmlmotd 0 +on +cl_resend 30 +cl_resend_timeout 2000 +clientport 27007 +cl_timeout 30{\rtf1}
::"c:/program files/sandboxie/start.exe" /elevate /silent /box:idle7 "c:/program files (x86)/steam/steam.exe" -single_core -login drop_account_7 idlebotseven -silent -applaunch 730 -sw -w 800 -h 600 -low +fps_max 10 -console -nosound -novid -nojoy -noshader -nofbo -nodcaudio -condebug -nomsaa +set vid level 0 +sethdmodels 0 +log off +noshaderapi +lv -16bpp +setrenderer opengl -threads 1 +cl_disablehtmlmotd 0 +on +cl_resend 30 +cl_resend_timeout 2000 +clientport 27007 +cl_timeout 30{\rtf1}
::"c:/program files/sandboxie/start.exe" /elevate /silent /box:idle8 "c:/program files (x86)/steam/steam.exe" -single_core -login drop_account_8 idleboteight -silent -applaunch 730 -sw -w 800 -h 600 -low +fps_max 10 -console -nosound -novid -nojoy -noshader -nofbo -nodcaudio -condebug -nomsaa +set vid level 0 +sethdmodels 0 +log off +noshaderapi +lv -16bpp +setrenderer opengl -threads 1 +cl_disablehtmlmotd 0 +on +cl_resend 30 +cl_resend_timeout 2000 +clientport 27007 +cl_timeout 30{\rtf1}
::"c:/program files/sandboxie/start.exe" /elevate /silent /box:idle9 "c:/program files (x86)/steam/steam.exe" -single_core -login drop_account_9 idlebotnine -silent -applaunch 730 -sw -w 800 -h 600 -low +fps_max 10 -console -nosound -novid -nojoy -noshader -nofbo -nodcaudio -condebug -nomsaa +set vid level 0 +sethdmodels 0 +log off +noshaderapi +lv -16bpp +setrenderer opengl -threads 1 +cl_disablehtmlmotd 0 +on +cl_resend 30 +cl_resend_timeout 2000 +clientport 27007 +cl_timeout 30{\rtf1}